return {
	src = "https://github.com/nvim-treesitter/nvim-treesitter",
	config = function()
		require("nvim-treesitter").install({
			"bash",
			"blade",
			"c",
			"comment",
			"css",
			"diff",
			"dockerfile",
			"fish",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gowork",
			"html",
			"ini",
			"javascript",
			"jsdoc",
			"json",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"nginx",
			"nix",
			"proto",
			"python",
			"query",
			"regex",
			"rust",
			"scss",
			"sql",
			"terraform",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zig",
		})
		vim.api.nvim_create_autocmd("FileType", {
			pattern = { 'c', 'cpp', 'lua', 'python' },
			callback = function()
				vim.treesitter.start()
			end,
		})
	end,
}
