scan_timeout = 100
command_timeout = 500
add_newline = false

format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character\
"""

[time]
disabled = false
time_format = '%H:%M'
style = 'dimmed white'
format = '[\[ $time \]]($style)'

[username]
show_always=true
style_user = 'dimmed white'
format = '[\[ $user]($style)'

[hostname]
ssh_only = false
disabled = false
style = 'dimmed white'
format = '@[$hostname]($style) '

[directory]
style = 'bold white'
format = '[$path ]($style)[$read_only]($read_only_style)\]'

[git_branch]
style = 'white'
format = '[\[ $branch($remote_branch)]($style) '

[git_commit]
disabled = false
only_detached = false
style = 'dimmed white'
format = '[$hash$tag ]($style)'

[git_state]
disabled = false

[git_status]
disabled = false
modified = '[!${count} ](bold yellow)'
staged = '[+${count} ](bold green)'
untracked = '[?${count} ](bold red)'
ahead = '[^${count} ](bold cyan)'
behind = '[v${count} ](bold magenta)'
style = 'bold white'
format = '[$all_status$ahead_behind]($style)\]'

[character]
format = "> "
